# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this means, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
url: "http://lexiemiller.github.io/bioinformaticslab4"

# baseurl should be an empty string
#baseurl: ""

# Name of website
title: Bioinformatics Lab 4

# Short description of your site
description: My New Website for Introduction to Bioinformatics

# --- Navigation bar options --- #



# List of links in the navigation bar
navbar-links:
  Home: ""
  Resources:
    - Getting started: "getstarted"
    - Other sites that use this template: "featured-users"
    - External link to Beautiful Jekyll Template page: "https://github.com/daattali/beautiful-jekyll#readme"
  Example pages:
    - Example of a Markdown page: "md-example"
    - Example of an HTML page: "html-example"
  About me: "https://www.linkedin.com/school/george-washington-university/about/"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Lexie Miller
  email: "Lexiemiller@gwu.edu"
  github: Lexiemiller

 



# --- Misc --- #





# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Washington"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 
      show-share: true # add sharing buttons to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
